# This is a basic workflow to help you get started with Actions

name: Test Suite

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  schedule:
    - cron: '00 17 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: 2.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sakee
        pip install html-testRunner
        pip install parameterized

    - name: Run tests
      run: |
        export PYTHONPATH=$GITHUB_WORKSPACE
        export KODI_INTERACTIVE=0
        export KODI_HOME=$GITHUB_WORKSPACE/tests/home
        python tests/test_generic.py

    - name: Pushe to website
      uses: cpina/github-action-push-to-another-repository@master
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'report'
        destination-github-username: 'kodiondemand'
        destination-repository-name: 'kodiondemand.github.io'
        user-email: test@test.test
